config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :expenses
  resource :user

  root 'pages#home'

  get '/login', to: 'sessions#new', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :expense
  belongs_to :user

  monetize :amount_cents
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  has_many :bills

  def amount=(value)
    @amount = value.tr(',', '.').to_f * 100.to_i
  end

  def amount
    Money.new(@amount, 'EUR')
  end

  attr_accessor :user_ids
  attr_accessor :include_current_user_in_bill

  def create_bills
    if include_current_user_in_bill == '1'
      create_bills_split_with_current_user
    else
      create_bills_split_without_current_user
    end
  end

  def create_bills_split_with_current_user
    splitted_amount = amount.split(user_ids.count + 1)
    create_bill(user_id, amount - splitted_amount.pop)
    user_ids.each do |user_id|
      create_bill(user_id, -splitted_amount.pop)
    end
  end

  def create_bills_split_without_current_user
    splitted_amount = amount.split(user_ids.count)
    create_bill(user_id, amount)
    user_ids.each do |user_id|
      create_bill(user_id, -splitted_amount.pop)
    end
  end

  def create_bill(user_id, bill_amount)
    bills.create(user_id: user_id, amount: bill_amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # validates :username,  presence: true,
  # length: { maximum: 12 },
  # uniqueness: true
  has_many :expenses
  has_many :bills
  validates :email,  presence: true,
                     length: { maximum: 50 },
                     uniqueness: true,
                     confirmation: true

  def except_current_user(user_id)
    where.not(id: user_id)
  end

  def total_value_from_bills
    bills.sum(:amount_cents)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # require login

  before_action :require_login

  def logged_in?
    @current_user.present?
  end

  helper_method :logged_in?

  def require_login
    @current_user ||= User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to :root, notice: 'Login required!'
  end

  attr_reader :current_user
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @users = User.where.not(id: current_user)
  end

  def create
    @expense = current_user.expenses.create(expense_params)

    @expense.create_bills

    flash[:secondary] = 'Expense created!'
    redirect_to @expense
  end

  def show
    @expense = Expense.find(params[:id])
  end

  private

  def expense_params
    params.require(:expense).permit(:description, :amount, :include_current_user_in_bill, user_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user
      session[:user_id] = user.id
      flash[:secondary] = 'Welcome back!'
      redirect_to controller: 'users', action: 'show' # user_show_path
    else
      flash[:danger] = 'Email is invalid.'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = 'Logged out!'
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @current_user_expenses = current_user.expenses.order(:created_at).page(params[:exp_page]).per(5)
    @current_user_bills = current_user.bills.order(:created_at).page(params[:bill_page]).per(5)
    @total_value = Money.new(current_user.total_value_from_bills, 'EUR').format(symbol_position: :after)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(session[:user_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.haml
= form_for @expense do |f|
  = f.text_field :description, placeholder: "description"
  %br
  = f.check_box :include_current_user_in_bill, checked: true
  include me in the bill
  %br
  = f.select :user_ids, options_from_collection_for_select(@users, :id, :email), {include_hidden: false}, multiple: true
  %br
  = f.text_field :amount, placeholder: 'amount'
  .actions.btn-margin-top= f.submit "Create", class: "btn btn-primary"

app/views/expenses/new.html.haml
.jumbotron
  .row
    .col-lg-3
    .col-lg-6
      %h1 New Expense
      = render 'form'

app/views/expenses/show.html.haml
%h2 Show Page
%table{summary:"Expenses detail view"}
  %tr
    %th description
    %td= @expense.description
  - @expense.bills.each do |bill|
    %tr
      %th user
      %td= bill.user.email
      %td= bill.amount

app/views/layouts/application.html.haml
!!!
%html

  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"} 
    /Bootstrap for Mobile-view
    %title Pannier
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body{class: "#{'bgimage' if controller_name == 'pages'}"}
    %header
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-white
        .container
          - if controller_name == 'pages'
            = link_to :root, class: "navbar-brand" do
              = image_tag("Logo.png")
              = image_tag("pannier.png")
          - else
            = link_to :user, class: "navbar-brand" do
              = image_tag("Logo.png")
              = image_tag("pannier.png")
            -if logged_in?
              = link_to 'New expense', new_expense_path, class: "btn btn-primary"
          .navbar-nav.ml-auto
            - if logged_in?
              = link_to 'Profile', edit_user_path, class: "btn btn-outline-secondary btn-margin-right"
              = link_to 'Logout', session_path, method: :delete, class: "btn btn-outline-danger"
            - else
              = link_to 'Sign up', login_path, class: "btn btn-primary btn-margin-right"
              .top-margin-header
                or
              = link_to 'Login', login_path, class: "btn btn-outline-secondary btn-margin-left"

    %main.container
      - flash.each do |key, value|
        .content_tag{class: "alert alert-#{key} center"}= value
      = yield

    %footer
      .container.center
        .float-left Made with love by&nbsp
        %a.float-left{href: "https://www.railslove.com"}Railslove
        %a{href: "/impressum.txt"}Impressum
        %p.float-right.no-margin-bottom
          %a{href: "#"} Back to top

app/views/pages/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Home</h1>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Login', login_path %>

app/views/pages/home.html.haml
/%p#notice= notice

.jumbotron
  .row
    .col-lg-12
      .headline
        %h1 Never forget about who owes what!
      .longer-headline
        %strong 
          Share
        bills and IOUs.
        %strong
          Make sure
        everybody gets paid back.

.jumbotron
  .row
    .col-lg-12
      %h2 Pannier does the math for you
      %p Pannier keeps a running total over time, so you can pay each other back in one big payment, instead of a bunch of small ones.

.jumbotron
  .btn-center
    %a.btn.btn-xlg.btn-primary{href: "/singup"}
      Sing up now »

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :email
    = form.text_field :email, id: :user_email
  .actions.btn-margin-top= form.submit "Save", class: "btn btn-primary"

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.haml
.jumbotron
  .row
    .col-lg-3
    .col-lg-6
      %h1 Editing User
      = render 'form', user: @user

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th Email
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/login.html.erb
<h1>Login</h1>

  <%= label(:email, :user_email) %>
  <%= text_field(:email, :user_email, size: 20) %>



<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', root_path

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice.alert-success= alert= notice
%h1 Hallo, that's your overview!

%strong Email:
= @user.email

%hr/
%b Your Total @ Railslove
= @total_value

%hr/
.row
  .col-lg-6
    %b Your Bills
    %table.table
      %thead.thead-light
        %tr
          %th{scope: "col"} Description
          %th{scope: "col"} Amount
          %th{scope: "col"} Date
      %tbody
        - @current_user_bills.each do |bill|
          %tr
            %td= bill.expense.description
            %td= bill.amount.format(symbol_position: :after)
            %td= bill.created_at
    = paginate @current_user_bills, param_name: 'bill_page'
    = page_entries_info @current_user_bills



  .col-lg-6
    %b Your Expenses
    %table.table
      %thead.thead-light
        %tr
          %th{scope: "col"} Description
          %th{scope: "col"} Date
          %th{scope: "col"} Action
      %tbody
        - @current_user_expenses.each do |expense|
          %tr
            %td= expense.description
            %td= expense.created_at
            %td.actions
              = link_to("Show", expense_path(expense), class: 'action show')
              /= link_to("Edit", edit_expense_path(expense), class: 'action edit')
              /= link_to("Delete", delete_expense_path(expense), class: 'action delete')
    = paginate @current_user_expenses, param_name: 'exp_page'
    = page_entries_info @current_user_expenses